---
radosgw_resolve_cname: true # enable for radosgw to resolve DNS CNAME based bucket names
radosgw_civetweb_port: 80
radosgw_civetweb_num_threads: 100
#radosgw_dns_name: your.subdomain.tld


#rgw_multisite: false
#rgw_zonegroup: ""
#rgw_zone: ""

# Multi-site remote pull URL variables
#rgw_pull_port: "{{ radosgw_civetweb_port }}"
#rgw_pull_proto: "http"


##########
# TUNING #
##########

# To support buckets with a very large number of objects it's
# important to split them into shards. We suggest about 100K
# objects per shard as a conservative maximum.
#rgw_override_bucket_index_max_shards: 16

# Consider setting a quota on buckets so that exceeding this
# limit will require admin intervention.
#rgw_bucket_default_quota_max_objects: 1638400 # i.e., 100K * 16

# This dictionary will create pools with the given number of pgs.
# This is important because they would be created with the default
# of 8.
# New pools and their corresponding pg_nums can be created
# by adding to the rgw_create_pools dictionary (see foo).
#rgw_create_pools:
#  defaults.rgw.buckets.data:
#    pg_num: 16
#  defaults.rgw.buckets.index:
#    pg_num: 32
#  foo:
#    pg_num: 4
